# Generated by Django 4.2.3 on 2023-10-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='inventario',
        ),
    ]
