# Generated by Django 4.2.3 on 2023-11-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0003_categories_inventories_measurement_units_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
