# Generated by Django 4.2.3 on 2023-11-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0006_remove_sale_details_price_remove_sales_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
