# Generated by Django 4.2.3 on 2023-11-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0007_alter_sales_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('subtotal', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='ferreteria.inventories')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_details', to='ferreteria.sales')),
            ],
        ),
        migrations.DeleteModel(
            name='Sale_Details',
        ),
    ]
