# Generated by Django 4.2.3 on 2023-11-21 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0010_rename_sale_details_saledetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetails',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferreteria.inventories'),
        ),
        migrations.AlterField(
            model_name='saledetails',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ferreteria.sales'),
        ),
    ]
